# Generated by Django 3.0.4 on 2020-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthits',
            name='ip',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='posthits',
            name='session',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
