# Generated by Django 3.0.4 on 2020-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200412_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthits',
            name='ip',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posthits',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
